
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu May 17 15:06:51 CST 2018
//----------------------------------------------------

package ejemplocup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SUS_ABSTRACT = 10;
  public static final int AUX_PRESEN = 38;
  public static final int VERBO_PASADOSIMP = 28;
  public static final int ADJ_PROINTERR = 20;
  public static final int ENTERO = 53;
  public static final int AUXPPS = 51;
  public static final int VEGET = 42;
  public static final int CONJ_SUBORCAUS = 34;
  public static final int CONJ_CONJSUBOCONCES = 36;
  public static final int PARENIZQ = 6;
  public static final int CONJ_COORADVERV = 30;
  public static final int SEMI = 2;
  public static final int VERBO_PASADOPARTICI = 29;
  public static final int ADJ_NUMCARDIN = 15;
  public static final int VERBO_PRESENTS = 27;
  public static final int GOING = 50;
  public static final int AUXPASP = 46;
  public static final int ADJ_DEMOS = 13;
  public static final int CONJ_COORDISYU = 32;
  public static final int ADJ_PROPOSESIV = 18;
  public static final int ADJ_CALIFI = 14;
  public static final int VERBO_PRESENT = 26;
  public static final int ADJ_NUMORD = 16;
  public static final int EOF = 0;
  public static final int CONJ_CONJSUBOCONSEC = 35;
  public static final int error = 1;
  public static final int CONJ_COORCOPU = 31;
  public static final int OP_MULT = 5;
  public static final int CONJ_SUBORDISYU = 33;
  public static final int PREP_MOV = 23;
  public static final int AUXPRESP = 45;
  public static final int OP_RESTA = 4;
  public static final int AUX_PAS = 39;
  public static final int PARENDER = 7;
  public static final int PAIS = 43;
  public static final int PREP_TIEM = 24;
  public static final int WILL = 49;
  public static final int INTERRO = 47;
  public static final int NO = 48;
  public static final int ADJ_POSESIV = 12;
  public static final int PREP_MOD = 21;
  public static final int WEATH = 40;
  public static final int ADJ_PROPERSO = 17;
  public static final int ANIMALS = 44;
  public static final int PROF = 41;
  public static final int ADJ_PROREFLEX = 19;
  public static final int SUS_COMUN = 11;
  public static final int PREP_LUG = 22;
  public static final int ART_INDEFI = 8;
  public static final int OP_SUMA = 3;
  public static final int ART_DEFI = 9;
  public static final int AUXPASPP = 52;
  public static final int SIG_PUNT = 25;
  public static final int CONJ_CONJSUBOCOMPARA = 37;
}

